### PR TITLE
Export SupportedLanguage

### PR DESCRIPTION
**Pull request by mash**
I'd like to know which language go-i18n decided to use among the candidates caller provided to Tfunc, for example save the language into database for pushing localized content afterwards.

### CODE REVIEW

**Comment by mash** [comment]
OK, I did invert the condition.
Also, it was already gofmt-ed :)

**Comment by nicksnyder** [comment]
Thanks for this contribution!

In your use case, do you expect to call Tfunc and SupportedLanguage with the same frequency (e.g. every request)?

**Comment by mash** [comment]
Yes, so it's best if MustTfunc (called with a fallback language so that it doesn't panic) returned both the TranslateFunc and Language, but I thought changing the interface is not an option.

**Comment by nicksnyder** [comment]
Ok. Let me think about if we should break API compatibility.

**Comment by mash** [comment]
or maybe just add two more functions (MustTfuncAndLanguage and TfuncAndLanguage)? either is fine for me

**Comment by nicksnyder** [comment]
I like the idea of MustTfuncAndLanguage and TfuncAndLanguage. Would you be able to update your pull request?

**Comment by mash** [comment]
OK, I'll work on that

**Comment by nicksnyder** [comment]
Sorry for the delay, I didn't realize you had updated the pull request. I merged your commit with some minor changes. I kept supportedLanguages unexported as it seemed redundant given the new API. Please let me know if you have a reason for it needing to still be exported and I and easily export it.

Thanks again for your contribution!

**Comment by mash** [comment]
Thanks!
I'm fine with keeping supportedLanguages unexported.

**Pull request merged**
