### PR TITLE
i18n/language: add Macedonian

### PR DESCRIPTION
**Pull request by parkr**
Rules per http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html

- [x] CLDR rules
- [x] Tests

### CODE REVIEW

**Comment by nicksnyder** [comment]
Please use [CLDR](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html) rules as source of truth. I am happy to merge after there are tests and merge conflicts are resolved.

Thanks!

**Comment by parkr** [comment]
Hey, Nick! Hear you loud and clear. The [CLDR rules for `mk`](http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#mk) seem to indicate a difference in calculating the proper `Plural` for cardinal, ordinal, and range, respectively. Which should I use here?

**Comment by parkr** [comment]
Updated with Cardinal CLDR rules. Let me know if you would like me to make any further adjustments. Thanks!

**Comment by nicksnyder** [comment]
Yes, cardinal is the correct ruleset to use.

**Pull request merged**
