### PR TITLE
bundle: Delete leading comments and whitespaces before detecting a format

### PR DESCRIPTION
**Pull request by bogem**

### CODE REVIEW

**Comment by bep** [comment]
What if this is how I start my YAML file?

```yaml
# Some comment
- id: translations
  translation: 
    one: "Translation"
    other: "Translations"
 ```

**Comment by bogem** [comment]
Then it should be also deleted. Same for JSON

**Comment by nicksnyder** [comment]
@bogem can you update to trim comments too?

**Comment by bogem** [comment]
Yes, I'm in process

**Pull request merged**
