### PR TITLE
Export MessageNotFoundErr

### PR DESCRIPTION
**Pull request by bep**
So a client can react to that particular error situation.

### CODE REVIEW

**Comment by bep** [comment]
Note that this comes from #125 -- which I guess could replace this PR if that worked. But I think it would be cleaner to just check the error.

Also, I don't understand the "codecov error". You may want to add something ala this: https://github.com/bep/s3deploy/blob/master/codecov.yml

**Comment by nicksnyder** [comment]
I don't have a problem with this PR but it would be helpful to me (for my own understanding) if you could explain your use-case for explicitly wanting to check for this error.

**Comment by bep** [comment]
If a message with a given ID in a given language does not exist, I want to be able to both 

1. Print a WARNING that there is a missing translation
2. Print the default language's version as a fallback

**Comment by nicksnyder** [comment]
Do you still think this is useful to export?

**Comment by bep** [comment]
>Do you still think this is useful to export?

Yes, as the API is now, these are the cases:

1. Found in the current language
2. Not found in the current language, but in some other language (check language tag)
3. Not found in any language (check error type)
4. Another error ... fail.

The API above could maybe be improved, but I cannot see how 3) can be handled without a way to check the error type (something ala `os.IsNotExist`).

**Pull request merged**
