### PR TITLE
IMPORTANT: Issue: concurrent map read and map write, Solution: Conver…

### PR DESCRIPTION
**Pull request by shantanubansal**
IMPORTANT: Issue: concurrent map read and map write, Solution: Converting Maps to Sync Maps

### CODE REVIEW

**Review by prathabk — APPROVED** [review]

**Comment by shantanubansal** [comment]
@nicksnyder can you please check this?
Do proposed changes looks good to you?

**Comment by nicksnyder** [comment]
Bundle is documented to not be goroutine safe. It has been a while since I thought about this library, and I am not sure if the right decision is to force synchronization in the library here or let consumers handle necessary synchronization. This is the kind of change I would want to think more about before merging, and at the same time, making changes to this library is not a priority for me right now.

**Comment by nicksnyder** [comment]
Going to close this PR as it has conflicts and would need to think through what a solution should be.

**Pull request closed without merging**
